name: nemsis
channels:
  - conda-forge
  - defaults
dependencies:
  - Python=3.10.11
  - pandas=2.0.3
  - numpy=1.22.4
  - scikit-learn=0.24.2
  - matplotlib=3.4.3
  - rpy2=3.5.14
  - scipy=1.9.1
  - seaborn=0.11.2
